# Generated by Django 4.0.4 on 2022-05-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0004_remove_inmuebles_m2_contruido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='numero_hab',
            field=models.IntegerField(default=0),
        ),
    ]
